<a href="https://colab.research.google.com/github/rochismandatta/Zindi.africa/blob/master/Contraceptive_Forecast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Train.csv to Train.csv

In [ ]:
import io
#uploaded = files.upload()
df2 = pd.read_csv(io.BytesIO(uploaded['Train.csv']))

NameError: ignored

In [ ]:
df2.head(5)

   year  month  ... stock_stockout_days stock_ordered
0  2019      1  ...                   0         100.0
1  2019      1  ...                   0          10.0
2  2019      1  ...                   0           0.0
3  2019      1  ...                   0           0.0
4  2019      1  ...                   0           0.0

[5 rows x 14 columns]

In [ ]:
df2['ID'] = df2['site_code'] + ' X ' + df2['product_code']
#df2.year.astype(str) + ' X ' + df2.month.astype(str) + ' X ' + df2['site_code'] + ' X ' + df2['product_code']

In [ ]:
df2['ID'].head(5)

0    C4001 X AS27134
1    C4001 X AS27132
2    C4001 X AS27000
3    C4001 X AS27137
4    C4001 X AS27138
Name: ID, dtype: object

In [ ]:
df2.columns

Index(['year', 'month', 'region', 'district', 'site_code', 'product_code',
       'stock_initial', 'stock_received', 'stock_distributed',
       'stock_adjustment', 'stock_end', 'average_monthly_consumption',
       'stock_stockout_days', 'stock_ordered', 'ID'],
      dtype='object')

In [ ]:
df3 = df2.drop(columns = ['region', 'district', 'site_code', 'product_code', 'stock_initial', 'stock_received', 'average_monthly_consumption',
    'stock_adjustment', 'stock_end', 'stock_stockout_days', 'stock_ordered'])

In [ ]:
df3.head()

   year  month  stock_distributed               ID
0  2019      1                 21  C4001 X AS27134
1  2019      1                  3  C4001 X AS27132
2  2019      1                 22  C4001 X AS27000
3  2019      1                  0  C4001 X AS27137
4  2019      1                  2  C4001 X AS27138

In [ ]:
y = np.array(df3['year']-1970, dtype='<M8[Y]')
m = np.array(df3['month']-1, dtype='<m8[M]')
#d = np.array(df['D']-1, dtype='<m8[D]')
df3['date'] = pd.Series(y+m)

In [ ]:
df3.head(5)

   year  month  stock_distributed               ID       date
0  2019      1                 21  C4001 X AS27134 2019-01-01
1  2019      1                  3  C4001 X AS27132 2019-01-01
2  2019      1                 22  C4001 X AS27000 2019-01-01
3  2019      1                  0  C4001 X AS27137 2019-01-01
4  2019      1                  2  C4001 X AS27138 2019-01-01

In [ ]:
df4 = df3.drop(columns = ['year', 'month'])

In [ ]:
df4.head(5)

   stock_distributed               ID       date
0                 21  C4001 X AS27134 2019-01-01
1                  3  C4001 X AS27132 2019-01-01
2                 22  C4001 X AS27000 2019-01-01
3                  0  C4001 X AS27137 2019-01-01
4                  2  C4001 X AS27138 2019-01-01

In [ ]:
ts_df = df4.pivot(index= 'date', columns='ID', values='stock_distributed')

In [ ]:
ts_df

ID          C1004 X AS21126  C1004 X AS27000  ...  C5066 X AS42018  C5066 X AS46000
date                                          ...
2016-01-01              NaN              NaN  ...              NaN              NaN
2016-02-01              NaN              NaN  ...              NaN              NaN
2016-03-01              NaN              NaN  ...              NaN              NaN
2016-04-01              NaN              NaN  ...              NaN              NaN
2016-05-01              NaN              NaN  ...              NaN              NaN
2016-06-01              NaN              NaN  ...              NaN              NaN
2016-07-01              NaN              0.0  ...              NaN              NaN
2016-08-01              NaN              NaN  ...              NaN              NaN
2016-09-01              NaN              NaN  ...              NaN              NaN
2016-10-01              NaN              NaN  ...              NaN              NaN
2016-11-01              NaN              NaN  ...              NaN              NaN
2016-12-01              NaN              NaN  ...              NaN              NaN
2017-01-01              NaN              NaN  ...              NaN              NaN
2017-02-01              NaN              NaN  ...              NaN              NaN
2017-03-01              NaN              NaN  ...              NaN              NaN
2017-04-01              NaN              NaN  ...              NaN              NaN
2017-05-01              NaN              NaN  ...              0.0              0.0
2017-06-01              NaN              NaN  ...              0.0              0.0
2017-07-01              NaN              0.0  ...              0.0              0.0
2017-08-01              NaN              7.0  ...              0.0              0.0
2017-09-01              NaN             44.0  ...              0.0              0.0
2017-10-01              NaN             13.0  ...              0.0              0.0
2017-11-01              NaN             16.0  ...              NaN              NaN
2017-12-01              NaN             32.0  ...              NaN              NaN
2018-01-01              NaN             30.0  ...              NaN              NaN
2018-02-01              NaN             34.0  ...              NaN              NaN
2018-03-01              NaN              5.0  ...              NaN              NaN
2018-04-01              NaN             61.0  ...              NaN              NaN
2018-05-01              NaN             22.0  ...              NaN              NaN
2018-06-01              NaN             26.0  ...              NaN              NaN
2018-07-01              NaN             61.0  ...              NaN              NaN
2018-08-01              NaN              0.0  ...              NaN              NaN
2018-09-01              NaN             40.0  ...              NaN              NaN
2018-10-01              NaN             55.0  ...              NaN              NaN
2018-11-01              NaN             17.0  ...              NaN              NaN
2018-12-01              NaN             60.0  ...              NaN              NaN
2019-01-01              NaN             13.0  ...              NaN              NaN
2019-02-01              NaN             19.0  ...              NaN              NaN
2019-03-01              NaN             19.0  ...              NaN              NaN
2019-04-01              0.0             43.0  ...              NaN              NaN
2019-05-01              0.0             30.0  ...              NaN              NaN
2019-06-01              NaN             21.0  ...              NaN              NaN

[42 rows x 1343 columns]

In [ ]:
ts_df.fillna(0, inplace = True)

In [ ]:
ts_df

ID          C1004 X AS21126  C1004 X AS27000  ...  C5066 X AS42018  C5066 X AS46000
date                                          ...
2016-01-01              0.0              0.0  ...              0.0              0.0
2016-02-01              0.0              0.0  ...              0.0              0.0
2016-03-01              0.0              0.0  ...              0.0              0.0
2016-04-01              0.0              0.0  ...              0.0              0.0
2016-05-01              0.0              0.0  ...              0.0              0.0
2016-06-01              0.0              0.0  ...              0.0              0.0
2016-07-01              0.0              0.0  ...              0.0              0.0
2016-08-01              0.0              0.0  ...              0.0              0.0
2016-09-01              0.0              0.0  ...              0.0              0.0
2016-10-01              0.0              0.0  ...              0.0              0.0
2016-11-01              0.0              0.0  ...              0.0              0.0
2016-12-01              0.0              0.0  ...              0.0              0.0
2017-01-01              0.0              0.0  ...              0.0              0.0
2017-02-01              0.0              0.0  ...              0.0              0.0
2017-03-01              0.0              0.0  ...              0.0              0.0
2017-04-01              0.0              0.0  ...              0.0              0.0
2017-05-01              0.0              0.0  ...              0.0              0.0
2017-06-01              0.0              0.0  ...              0.0              0.0
2017-07-01              0.0              0.0  ...              0.0              0.0
2017-08-01              0.0              7.0  ...              0.0              0.0
2017-09-01              0.0             44.0  ...              0.0              0.0
2017-10-01              0.0             13.0  ...              0.0              0.0
2017-11-01              0.0             16.0  ...              0.0              0.0
2017-12-01              0.0             32.0  ...              0.0              0.0
2018-01-01              0.0             30.0  ...              0.0              0.0
2018-02-01              0.0             34.0  ...              0.0              0.0
2018-03-01              0.0              5.0  ...              0.0              0.0
2018-04-01              0.0             61.0  ...              0.0              0.0
2018-05-01              0.0             22.0  ...              0.0              0.0
2018-06-01              0.0             26.0  ...              0.0              0.0
2018-07-01              0.0             61.0  ...              0.0              0.0
2018-08-01              0.0              0.0  ...              0.0              0.0
2018-09-01              0.0             40.0  ...              0.0              0.0
2018-10-01              0.0             55.0  ...              0.0              0.0
2018-11-01              0.0             17.0  ...              0.0              0.0
2018-12-01              0.0             60.0  ...              0.0              0.0
2019-01-01              0.0             13.0  ...              0.0              0.0
2019-02-01              0.0             19.0  ...              0.0              0.0
2019-03-01              0.0             19.0  ...              0.0              0.0
2019-04-01              0.0             43.0  ...              0.0              0.0
2019-05-01              0.0             30.0  ...              0.0              0.0
2019-06-01              0.0             21.0  ...              0.0              0.0

[42 rows x 1343 columns]

In [ ]:
import itertools
import statsmodels.api as sm
import warnings
warnings.filterwarnings(action='ignore')

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
p = d = q = range(0, 2)
pdq = list(itertools.product(p, d, q))
seasonal_pdq = [(x[0], x[1], x[2], 12) for x in list(itertools.product(p, d, q))]
print('SARIMAX: {} x {}'.format(pdq[1], seasonal_pdq[1]))
print('SARIMAX: {} x {}'.format(pdq[1], seasonal_pdq[2]))
print('SARIMAX: {} x {}'.format(pdq[2], seasonal_pdq[3]))
print('SARIMAX: {} x {}'.format(pdq[2], seasonal_pdq[4]))

SARIMAX: (0, 0, 1) x (0, 0, 1, 12)
SARIMAX: (0, 0, 1) x (0, 1, 0, 12)
SARIMAX: (0, 1, 0) x (0, 1, 1, 12)
SARIMAX: (0, 1, 0) x (1, 0, 0, 12)

In [ ]:
def ts_forcasting_mp(col):
    df = ts_df[col]
    #hold_data = 7
    input_df = df
    model_parameter = []
    for param in pdq:
        for param_seasonal in seasonal_pdq:
            try:
                mod = sm.tsa.statespace.SARIMAX(input_df,
                                                order=param,
                                                seasonal_order=param_seasonal,
                                                enforce_stationarity=False,
                                                enforce_invertibility=False)
                results = mod.fit()
                #print('ARIMA{}x{}, AIC: {}'.format(param, param_seasonal, results.aic))
                model_parameter.append([param, param_seasonal, results.aic, results])
            except:
                continue
    
    model_parameter.sort(key = lambda x: x[2]) 
    model_selected = model_parameter[0]
    print('Selected ARIMA{}x{}'.format(model_selected[0], model_selected[1]))

    results = model_selected[3]

    pred = results.get_prediction(start=pd.to_datetime('2019-07-01'),
                          end=pd.to_datetime('2019-12-01'), dynamic=False)

    ctr_forecasted = pred.predicted_mean
    
    
    return [col, ctr_forecasted]

In [ ]:
ts_df.columns

Index(['C1004 X AS21126', 'C1004 X AS27000', 'C1004 X AS27132',
       'C1004 X AS27133', 'C1004 X AS27134', 'C1004 X AS27137',
       'C1004 X AS27138', 'C1004 X AS27139', 'C1004 X AS42018',
       'C1007 X AS17005',
       ...
       'C5066 X AS21126', 'C5066 X AS27000', 'C5066 X AS27132',
       'C5066 X AS27133', 'C5066 X AS27134', 'C5066 X AS27137',
       'C5066 X AS27138', 'C5066 X AS27139', 'C5066 X AS42018',
       'C5066 X AS46000'],
      dtype='object', name='ID', length=1343)

In [ ]:
'''
result_lst = []
for col in ts_df.columns[0:10]:
  result_lst.append(ts_forcasting_mp(col, ts_df))
'''

Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)

In [ ]:
'''
result_lst[0:5]
'''

[['C1004 X AS21126', 2019-07-01    0.0
  2019-08-01    0.0
  2019-09-01    0.0
  2019-10-01    0.0
  2019-11-01    0.0
  2019-12-01    0.0
  Freq: MS, dtype: float64], ['C1004 X AS27000', 2019-07-01    36.432782
  2019-08-01    35.268242
  2019-09-01    76.650314
  2019-10-01    43.266889
  2019-11-01    47.553327
  2019-12-01    62.862935
  Freq: MS, dtype: float64], ['C1004 X AS27132', 2019-07-01     0.393224
  2019-08-01     0.416393
  2019-09-01    15.979958
  2019-10-01     2.783572
  2019-11-01     1.823731
  2019-12-01     2.537399
  Freq: MS, dtype: float64], ['C1004 X AS27133', 2019-07-01    62.084430
  2019-08-01    50.064198
  2019-09-01    80.560383
  2019-10-01    75.783827
  2019-11-01    58.312065
  2019-12-01    97.870709
  Freq: MS, dtype: float64], ['C1004 X AS27134', 2019-07-01     10.420928
  2019-08-01     22.620186
  2019-09-01    130.341408
  2019-10-01     19.871386
  2019-11-01    106.387468
  2019-12-01     48.269080
  Freq: MS, dtype: float64]]

In [ ]:
import multiprocessing as mp

In [ ]:
with mp.Pool(6) as p:
    return_dfs = p.map(ts_forcasting_mp, ts_df.columns)

Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 0)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 0)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(1, 0, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 0, 0)x(1, 1, 0, 12)
Selected ARIMA(1, 0, 0)x(0, 0, 1, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(0, 0, 1)x(0, 0, 1, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 0, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(0, 0, 0)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 0)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 0, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 0, 0)x(0, 0, 1, 12)
Selected ARIMA(1, 1, 0)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 1, 0)x(1, 1, 0, 12)
Selected ARIMA(1, 0, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 0)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 0, 0)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(1, 1, 0)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 1, 1)x(1, 1, 0, 12)
Selected ARIMA(1, 0, 1)x(1, 1, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)
Selected ARIMA(0, 0, 0)x(0, 0, 0, 12)

In [ ]:
len(return_dfs)

1343

In [ ]:
i1 = return_dfs[0]

In [ ]:
i1

['C1004 X AS21126', 2019-07-01    0.0
 2019-08-01    0.0
 2019-09-01    0.0
 2019-10-01    0.0
 2019-11-01    0.0
 2019-12-01    0.0
 Freq: MS, dtype: float64]

In [ ]:
type(i1[1])

pandas.core.series.Series

In [ ]:
i1[1].index

DatetimeIndex(['2019-07-01', '2019-08-01', '2019-09-01', '2019-10-01',
               '2019-11-01', '2019-12-01'],
              dtype='datetime64[ns]', freq='MS')

In [ ]:
i1[1].name = i1[0]

In [ ]:
i1[1].to_frame()

            C1004 X AS21126
2019-07-01              0.0
2019-08-01              0.0
2019-09-01              0.0
2019-10-01              0.0
2019-11-01              0.0
2019-12-01              0.0

In [ ]:
i2 = return_dfs[1]

In [ ]:
i2[1].name = i2[0]

In [ ]:
pd.concat([i1[1], i2[1]], axis=1)

            C1004 X AS21126  C1004 X AS27000
2019-07-01              0.0        36.432782
2019-08-01              0.0        35.268242
2019-09-01              0.0        76.650314
2019-10-01              0.0        43.266889
2019-11-01              0.0        47.553327
2019-12-01              0.0        62.862935

In [ ]:
dfs_lst = []
for i in return_dfs[:]:
  i[1].name = i[0]
  dfs_lst.append(i[1])

In [ ]:
len(dfs_lst)

1343

In [ ]:
dfs_lst[1342]

2019-07-01    0.0
2019-08-01    0.0
2019-09-01    0.0
2019-10-01    0.0
2019-11-01    0.0
2019-12-01    0.0
Freq: MS, Name: C5066 X AS46000, dtype: float64

In [ ]:
result_pddf = pd.concat(dfs_lst, axis=1)

In [ ]:
result_pddf

            C1004 X AS21126  C1004 X AS27000  ...  C5066 X AS42018  C5066 X AS46000
2019-07-01              0.0        36.432782  ...              0.0              0.0
2019-08-01              0.0        35.268242  ...              0.0              0.0
2019-09-01              0.0        76.650314  ...              0.0              0.0
2019-10-01              0.0        43.266889  ...              0.0              0.0
2019-11-01              0.0        47.553327  ...              0.0              0.0
2019-12-01              0.0        62.862935  ...              0.0              0.0

[6 rows x 1343 columns]

In [ ]:
result_pddf.to_csv("result_contra.csv", header=True, index=True)

In [ ]:
result_pddf.reset_index(drop=False, inplace= True)

In [ ]:
result_pddf.rename(columns={'index': 'date'}, inplace=True)

In [ ]:
result_pddf

        date  C1004 X AS21126  ...  C5066 X AS42018  C5066 X AS46000
0 2019-07-01              0.0  ...              0.0              0.0
1 2019-08-01              0.0  ...              0.0              0.0
2 2019-09-01              0.0  ...              0.0              0.0
3 2019-10-01              0.0  ...              0.0              0.0
4 2019-11-01              0.0  ...              0.0              0.0
5 2019-12-01              0.0  ...              0.0              0.0

[6 rows x 1344 columns]

In [ ]:
result_pddf.columns

Index(['date', 'C1004 X AS21126', 'C1004 X AS27000', 'C1004 X AS27132',
       'C1004 X AS27133', 'C1004 X AS27134', 'C1004 X AS27137',
       'C1004 X AS27138', 'C1004 X AS27139', 'C1004 X AS42018',
       ...
       'C5066 X AS21126', 'C5066 X AS27000', 'C5066 X AS27132',
       'C5066 X AS27133', 'C5066 X AS27134', 'C5066 X AS27137',
       'C5066 X AS27138', 'C5066 X AS27139', 'C5066 X AS42018',
       'C5066 X AS46000'],
      dtype='object', length=1344)

In [ ]:
prediction_df = result_pddf.melt(id_vars=["date"], 
        var_name="ID", 
        value_name="prediction")

In [ ]:
prediction_df.head(20)

         date               ID  prediction
0  2019-07-01  C1004 X AS21126    0.000000
1  2019-08-01  C1004 X AS21126    0.000000
2  2019-09-01  C1004 X AS21126    0.000000
3  2019-10-01  C1004 X AS21126    0.000000
4  2019-11-01  C1004 X AS21126    0.000000
5  2019-12-01  C1004 X AS21126    0.000000
6  2019-07-01  C1004 X AS27000   36.432782
7  2019-08-01  C1004 X AS27000   35.268242
8  2019-09-01  C1004 X AS27000   76.650314
9  2019-10-01  C1004 X AS27000   43.266889
10 2019-11-01  C1004 X AS27000   47.553327
11 2019-12-01  C1004 X AS27000   62.862935
12 2019-07-01  C1004 X AS27132    0.393224
13 2019-08-01  C1004 X AS27132    0.416393
14 2019-09-01  C1004 X AS27132   15.979958
15 2019-10-01  C1004 X AS27132    2.783572
16 2019-11-01  C1004 X AS27132    1.823731
17 2019-12-01  C1004 X AS27132    2.537399
18 2019-07-01  C1004 X AS27133   62.084430
19 2019-08-01  C1004 X AS27133   50.064198

In [ ]:
prediction_df.date

0      2019-07-01
1      2019-08-01
2      2019-09-01
3      2019-10-01
4      2019-11-01
          ...
8053   2019-08-01
8054   2019-09-01
8055   2019-10-01
8056   2019-11-01
8057   2019-12-01
Name: date, Length: 8058, dtype: datetime64[ns]

In [ ]:
prediction_df['month'] = pd.DatetimeIndex(prediction_df['date']).month

In [ ]:
prediction_df['year'] = pd.DatetimeIndex(prediction_df['date']).year

In [ ]:
prediction_df.head(10)

        date               ID  prediction  month  year
0 2019-07-01  C1004 X AS21126    0.000000      7  2019
1 2019-08-01  C1004 X AS21126    0.000000      8  2019
2 2019-09-01  C1004 X AS21126    0.000000      9  2019
3 2019-10-01  C1004 X AS21126    0.000000     10  2019
4 2019-11-01  C1004 X AS21126    0.000000     11  2019
5 2019-12-01  C1004 X AS21126    0.000000     12  2019
6 2019-07-01  C1004 X AS27000   36.432782      7  2019
7 2019-08-01  C1004 X AS27000   35.268242      8  2019
8 2019-09-01  C1004 X AS27000   76.650314      9  2019
9 2019-10-01  C1004 X AS27000   43.266889     10  2019

In [ ]:
prediction_df['ID_final'] = prediction_df.year.astype(str) + ' X ' + prediction_df.month.astype(str) + ' X ' + prediction_df['ID']

In [ ]:
prediction_df.head(10)

        date               ID  ...  year                     ID_final
0 2019-07-01  C1004 X AS21126  ...  2019   2019 X 7 X C1004 X AS21126
1 2019-08-01  C1004 X AS21126  ...  2019   2019 X 8 X C1004 X AS21126
2 2019-09-01  C1004 X AS21126  ...  2019   2019 X 9 X C1004 X AS21126
3 2019-10-01  C1004 X AS21126  ...  2019  2019 X 10 X C1004 X AS21126
4 2019-11-01  C1004 X AS21126  ...  2019  2019 X 11 X C1004 X AS21126
5 2019-12-01  C1004 X AS21126  ...  2019  2019 X 12 X C1004 X AS21126
6 2019-07-01  C1004 X AS27000  ...  2019   2019 X 7 X C1004 X AS27000
7 2019-08-01  C1004 X AS27000  ...  2019   2019 X 8 X C1004 X AS27000
8 2019-09-01  C1004 X AS27000  ...  2019   2019 X 9 X C1004 X AS27000
9 2019-10-01  C1004 X AS27000  ...  2019  2019 X 10 X C1004 X AS27000

[10 rows x 6 columns]

In [ ]:
prediction_df.month < 10

0        True
1        True
2        True
3       False
4       False
        ...
8053     True
8054     True
8055    False
8056    False
8057    False
Name: month, Length: 8058, dtype: bool

In [ ]:
prediction_df1 = prediction_df[prediction_df.month < 10]

In [ ]:
prediction_df1.head(10)

         date               ID  ...  year                    ID_final
0  2019-07-01  C1004 X AS21126  ...  2019  2019 X 7 X C1004 X AS21126
1  2019-08-01  C1004 X AS21126  ...  2019  2019 X 8 X C1004 X AS21126
2  2019-09-01  C1004 X AS21126  ...  2019  2019 X 9 X C1004 X AS21126
6  2019-07-01  C1004 X AS27000  ...  2019  2019 X 7 X C1004 X AS27000
7  2019-08-01  C1004 X AS27000  ...  2019  2019 X 8 X C1004 X AS27000
8  2019-09-01  C1004 X AS27000  ...  2019  2019 X 9 X C1004 X AS27000
12 2019-07-01  C1004 X AS27132  ...  2019  2019 X 7 X C1004 X AS27132
13 2019-08-01  C1004 X AS27132  ...  2019  2019 X 8 X C1004 X AS27132
14 2019-09-01  C1004 X AS27132  ...  2019  2019 X 9 X C1004 X AS27132
18 2019-07-01  C1004 X AS27133  ...  2019  2019 X 7 X C1004 X AS27133

[10 rows x 6 columns]

In [ ]:
submission_df = prediction_df[['ID_final', 'prediction']]

In [ ]:
submission_df.head(10)

                            ID  ts_prediction
0   2019 X 7 X C1004 X AS21126       0.000000
1   2019 X 8 X C1004 X AS21126       0.000000
2   2019 X 9 X C1004 X AS21126       0.000000
3  2019 X 10 X C1004 X AS21126       0.000000
4  2019 X 11 X C1004 X AS21126       0.000000
5  2019 X 12 X C1004 X AS21126       0.000000
6   2019 X 7 X C1004 X AS27000      36.432782
7   2019 X 8 X C1004 X AS27000      35.268242
8   2019 X 9 X C1004 X AS27000      76.650314
9  2019 X 10 X C1004 X AS27000      43.266889

In [ ]:
submission_df.rename(columns={'ID_final': 'ID', 'prediction': 'ts_prediction'}, inplace=True)

In [ ]:
submission_df.head(10)

                            ID  ts_prediction
0   2019 X 7 X C1004 X AS21126       0.000000
1   2019 X 8 X C1004 X AS21126       0.000000
2   2019 X 9 X C1004 X AS21126       0.000000
3  2019 X 10 X C1004 X AS21126       0.000000
4  2019 X 11 X C1004 X AS21126       0.000000
5  2019 X 12 X C1004 X AS21126       0.000000
6   2019 X 7 X C1004 X AS27000      36.432782
7   2019 X 8 X C1004 X AS27000      35.268242
8   2019 X 9 X C1004 X AS27000      76.650314
9  2019 X 10 X C1004 X AS27000      43.266889

In [ ]:
submission_df.to_csv("submission_v3.csv", header= True, index= False)

In [ ]:
files.download('submission_v3.csv')

In [ ]:
prediction_df[prediction_df.ID == '2019 X 7 X C1679 X AS27138']

Empty DataFrame
Columns: [date, ID, prediction, month, year, ID_final]
Index: []

In [ ]:
uploaded = files.upload()

Saving SampleSubmission.csv to SampleSubmission.csv

In [ ]:
sample_df = pd.read_csv(io.BytesIO(uploaded['SampleSubmission.csv']))

In [ ]:
sample_df.head(10)

                           ID  prediction
0  2019 X 7 X C4001 X AS21126           0
1  2019 X 7 X C4001 X AS27134           0
2  2019 X 7 X C4001 X AS27132           0
3  2019 X 7 X C4001 X AS27000           0
4  2019 X 7 X C4001 X AS27137           0
5  2019 X 7 X C4001 X AS27138           0
6  2019 X 7 X C4001 X AS27133           0
7  2019 X 7 X C4023 X AS27000           0
8  2019 X 7 X C4023 X AS27133           0
9  2019 X 8 X C4023 X AS27000           0

In [ ]:
joined_df = pd.merge(sample_df,submission_df,on='ID',how='left')

In [ ]:
joined_df[joined_df.ID == '2019 X 7 X C1679 X AS27138']

                             ID  prediction  ts_prediction
162  2019 X 7 X C1679 X AS27138           0            NaN

In [ ]:
joined_df[joined_df.ts_prediction.isna()]

                              ID  prediction  ts_prediction
162   2019 X 7 X C1679 X AS27138           0            NaN
182   2019 X 8 X C1679 X AS27138           0            NaN
194   2019 X 9 X C1679 X AS27138           0            NaN
565   2019 X 8 X C5015 X AS27138           0            NaN
571   2019 X 9 X C5015 X AS27138           0            NaN
623   2019 X 7 X C5017 X AS21126           0            NaN
630   2019 X 8 X C5017 X AS21126           0            NaN
637   2019 X 9 X C5017 X AS21126           0            NaN
733   2019 X 9 X C4016 X AS21126           0            NaN
888   2019 X 9 X C3015 X AS21126           0            NaN
1188  2019 X 8 X C4024 X AS27138           0            NaN
1200  2019 X 9 X C4024 X AS27138           0            NaN
2081  2019 X 9 X C3020 X AS21126           0            NaN
2550  2019 X 7 X C1009 X AS27132           0            NaN
2589  2019 X 9 X C1009 X AS27132           0            NaN
3083  2019 X 9 X C5076 X AS27132           0            NaN
3084  2019 X 9 X C5076 X AS27000           0            NaN
3085  2019 X 9 X C5076 X AS27139           0            NaN
3086  2019 X 9 X C5076 X AS27137           0            NaN
3087  2019 X 9 X C5076 X AS27138           0            NaN
3088  2019 X 9 X C5076 X AS27133           0            NaN

In [ ]:
joined_df.fillna(0, inplace=True)

In [ ]:
joined_df[joined_df.ts_prediction.isna()]

Empty DataFrame
Columns: [ID, prediction, ts_prediction]
Index: []

In [ ]:
submission_df = joined_df[["ID",	"ts_prediction"]]

In [ ]:
submission_df.rename(columns={'ts_prediction': 'prediction'}, inplace=True)

In [ ]:
submission_df.head(10)

                           ID    prediction
0  2019 X 7 X C4001 X AS21126  0.000000e+00
1  2019 X 7 X C4001 X AS27134  3.334441e+00
2  2019 X 7 X C4001 X AS27132 -1.524471e-13
3  2019 X 7 X C4001 X AS27000  1.264024e+01
4  2019 X 7 X C4001 X AS27137  0.000000e+00
5  2019 X 7 X C4001 X AS27138  3.165599e+00
6  2019 X 7 X C4001 X AS27133  2.964221e+00
7  2019 X 7 X C4023 X AS27000  1.469232e+01
8  2019 X 7 X C4023 X AS27133  2.843166e+01
9  2019 X 8 X C4023 X AS27000  1.573593e+01

In [ ]:
submission_df.to_csv("submission_v2.csv", header= True, index= False)

In [ ]:
files.download('submission_v2.csv')